### ISSUE TITLE
可以增加缓存机制吗？

### ISSUE THREAD

**Issue by memorise** [jeasonlzy0216/OkHttpUtils#1]
比如先检查本地缓存，如果没有再请求网络。或者先检查网络，如果没有再检查本地之类的

**Comment by jeasonlzy0216** [comment]
最近比较忙，半个月内慢慢加上，可以先自己用本地文件或者数据库做下缓存，我会尽快更新

**Comment by memorise** [comment]
期待，另外你用的okhttp好像是3.0.0版吧，现在已经出到3.2.0了，建议更新

**Comment by jeasonlzy0216** [comment]
缓存已经增加。。ok已经升级到 3.2.0。可以看看。。

**Comment by jeasonlzy0216** [comment]
缓存已经增加。。ok已经升级到 3.2.0。可以看看。。

**Comment by memorise** [comment]
功能很强大，学习了很多，谢谢
