### ISSUE TITLE
Post方式提大量数据的时候会卡MainUIThread

### ISSUE THREAD

**Issue by parcool** [jeasonlzy0216/OkHttpUtils#11]
看代码，在BaseRequest里的251行generateMultipartRequestBody()这个方法，如果字段的数据量太大（比如3Mb的数据），会卡UI线程好几秒。暂时只能想到直接在.params(这里直接传FormBody)添加重载，少做一次转换。能优化就优化下吧，虽然这种情况非常小，只有我现在有这个需求。

**Comment by jeasonlzy0216** [comment]
一般来说，超过1m的数据请求和解析都是需要放在子线程的，这是okhttp官方推荐，因为generateMultipartRequestBody这个方法是在 ui线程执行的，所以会卡顿，后期会优化，感谢。。
