### ISSUE TITLE
cookie 持久化问题

### ISSUE THREAD

**Issue by draty01** [jeasonlzy0216/OkHttpUtils#14]
貌似本次请求会默认添加上次请求的cookie,会导致本次请求添加的cookie就覆盖,
我在生成call的时候,添加了请求头cookie,但不生效,只有第一次访问生效,后面的请求抓包时发现,我的cookie根本没设置进去,而是自动添加了之前响应回来的cookie,
这是个问题~~~

**Comment by jeasonlzy0216** [comment]
嗯，感谢你的问题。。目前最新版 1.5.2 已经解决了这个问题，在每次请求的时候可以额外使用 addCookie 方法添加自己的 cookie
