### ISSUE TITLE
服务器返回code=-2跳转登录页面如何实现

### ISSUE THREAD

**Issue by yk007** [jeasonlzy0216/OkHttpUtils#17]
在JsonCallback类中服务器如果返回code=-2时要跳转到登录页面要如何实现而不是在onresopnse回调里去判断是否需要跳转到登录页面

**Comment by jeasonlzy0216** [comment]
那么你可以在 parseNetworkResponse 方法中做个全局的检查，如果返回了对应的状态码，就跳转到登录页。
