### ISSUE TITLE
请问怎么设置contentType?

### ISSUE THREAD

**Issue by jiancao** [jeasonlzy0216/OkHttpUtils#20]
现在默认的是contentType : application/x-www-form-urlencoded

**Comment by tanranran** [comment]
+1

**Comment by xieyuhai** [comment]
+1

**Comment by yinsujun11** [comment]
+1

**Comment by jeasonlzy0216** [comment]
为什么要设置这个，content-type已经根据参数类型自己会改变的。。比如  默认字符串提交就是application/x-www-form-urlencoded，文件上传就是multipart/form-data;如果调用  postString就是text/plain，posrJson就是application/json，什么都不知道就是application/octet-stream，你们需要自定义这个头的场景是什么呢。。

**Comment by luxunchina** [comment]
application/soap+xml;charset=UTF-8

**Comment by o199666** [comment]
我需要提交text/xml 的类型啊
