### ISSUE TITLE
addCommonParams bug

### ISSUE THREAD

**Issue by star95** [jeasonlzy0216/OkHttpUtils#23]
使用addCommonParams(HttpParams commonParams)添加 HttpParams
每次请求一次 就会添加一样的参数进来，导致重复添加
eg:
http://192.168.5.125:8288/app/officemanager/contacts/user-list?&clientFlag=04&clientFlag=04&clientFlag=04&versionNo=1&versionNo=1&versionNo=1&groupId=0

clientFlag 和 versionNo 重复添加；

通过Interceptor 拦截器得到
request request = chain.request();
request.url();
拼接的参数在第一个 参数前多了 &

**Comment by jeasonlzy0216** [comment]
经过我的测试，是没有问题的。。能不能把你的请求代码发出来，看你是如何写的呢？使用的是哪个版本呢，在 1.6.0 版本以下是不可能出现相同参数的，因为参数都是map存的，相同key会覆盖的。
