### ISSUE TITLE
我想问下如何让请求重新执行一下

### ISSUE THREAD

**Issue by qingwadaxia** [jeasonlzy0216/OkHttpUtils#24]
根据token失效，重新获取token之后让之前调用的接口重新在执行一次，如何实现呢？因为现在用了你提供的这套HTTP请求框架，所以期待作者的回复

**Comment by jeasonlzy0216** [comment]
这是业务逻辑了，不属于框架的范畴，具体可在公共的parseNetworkReponse中根据服务器返回的错误码进行跳转。。也可以单独为你的请求写一个callback就可以了。。
