### ISSUE TITLE
get请求多参数会有一个自动排序的问题，导致请求失败

### ISSUE THREAD

**Issue by sanniou** [jeasonlzy0216/OkHttpUtils#27]
并不是按顺序添加的，很奇怪…

**Comment by sanniou** [comment]
看了一下并不是简单地字符串拼接，而是先将键值对put 到ConcurrentHashMap 中
只能先回退了，希望作者考虑下这种情况

**Comment by jeasonlzy0216** [comment]
默认所有的参数都会先存放在HttpParams中的conrenthashmap中，如果对顺序有要求，可以自己重写这个类，不过提交参数为啥需要顺序呢

**Comment by jeasonlzy0216** [comment]
目前1.7.0以上版本支持排序。。
