### ISSUE TITLE
断网的大Bug

### ISSUE THREAD

**Issue by ixiaoluo** [jeasonlzy0216/OkHttpUtils#30]
其一：在请求多个文件下载中，此时突然断网，没有进行失败的回调。其二：同样，在请求多个文件下载中，有几个文件下载不完整，我查看了Log，进度条到50~60后直接进行成功回调，进度条没有进入100，所以导致文件不完整。

**Comment by jeasonlzy0216** [comment]
这个应该是 okhttpserver的问题吧，server包目前优化并不好，不建议用，okhttputils还是没有问题的。。
