### ISSUE TITLE
加了cancelTag(context)，BaseRequest还是回调了OnError方法

### ISSUE THREAD

**Issue by Christain** [jeasonlzy0216/OkHttpUtils#32]
场景：进入一个页面获取数据，tag是传的activity.在网络还没有回调的时候，迅速退出Activity。这个时候BaseRequest回调了OnError，抛出了sokect异常。我就捕获了这个异常回了主线程，并弹出了Dialog.Dialog的Context就是Activity.但这个时候Activity已经不存在了。就出现了空指针。
我的问题是：是不是可以在CallBack方法里有什么判断让这个异常不回到主线程？或者说是我用法没有对？谢谢

**Comment by jeasonlzy0216** [comment]
csncel本来就是已抛异常的方式中断请求,你可以根据onerror中的异常类型判断是否是主动取消的。。

**Comment by anjiao** [comment]
你可以根据onError()中的异常类型判断是否是主动取消的?? 这个 怎么知道是 主动取消的异常呢？看到麻烦大神解答下

**Comment by jeasonlzy0216** [comment]
e.getMessage().equals("cancel")   如果是主动取消的，异常信息是 cancel 判断一下就可以了。
