### ISSUE TITLE
这个支持上传单文件或者多个文件吗?比如往服务器传几张图片

### ISSUE THREAD

**Issue by Greathfs** [jeasonlzy0216/OkHttpUtils#35]

**Comment by jeasonlzy0216** [comment]
支持。。可以 一个key传一个文件，也可以一个key传多个文件，也可以多个文件和多个参数同时上传。总之就是标准的 RESTful 风格的请求统统支持。。

**Comment by wl376705253** [comment]
请问一下 可以支持同时下载多个文件吗 类似选择两首音乐文件 进行下载这样的

**Comment by jeasonlzy0216** [comment]
可以 同时下载多少个都可以。。
