### ISSUE TITLE
请问混淆时需要的keep语句

### ISSUE THREAD

**Issue by dudukee** [jeasonlzy0216/OkHttpUtils#37]
请问混淆时需要的keep语句?

#okhttputils
-dontwarn com.lzy.okhttputils.**
-keep class com.lzy.okhttputils.**{*;}

#okhttp
-dontwarn okhttp3.**
-keep class okhttp3.**{*;}

#okio
-dontwarn okio.**
-keep class okio.**{*;}

**Comment by jeasonlzy0216** [comment]
嗯，只用okhttputils 这样就够了。如果用了 okhttpserver 就再加上 okhttpservere 的 keep 就好了。。
