### ISSUE TITLE
泛型类型与parseNetworkResponse返回类型不匹配

### ISSUE THREAD

**Issue by Christain** [jeasonlzy0216/OkHttpUtils#4]
当T=String,在执行CallBack的parseNetworkResponse这个方法，经过处理是走:return (T) response；在BaseRequest中： T t = (T) mCallback.parseNetworkResponse(response); sendSuccessResultCallback(t, call, response, mCallback);会catch不到Stirng和response类型不匹配而crash。

**Comment by jeasonlzy0216** [comment]
T = String 我测试过是没有问题的，你可以使用 AbsCallBck 打印一下 返回的数据能不能转成 string，如果不能的话，我那方法就会异常的，如果可以是不会的。。如果有更详细的情况，可以加群 489873144 ，在群里告诉我。

**Comment by Christain** [comment]
因为你现在默认进了parseNetworkResponse这里就是服务器正确返回了数据，其实大多数情况下服务器数据会给一个code值来判断是不是正确返回，假如在parseNetworkResponse方法里返回的不是String而是(T) response，在BaseRequest里面会调用onResponse(T t)方法把Response传到UI线程，但此时UI线程是onResponse(String result)这个回调，类型就不匹配了

**Comment by jeasonlzy0216** [comment]
这个你就可以根据自己的需要继承 AbsCallBack ，在这里面实现你自己的数据解析逻辑就可以了，例如对状态码的判断，错误消息的处理等等。。。我在demo 里面的callback包下有提供一个 CallBack 就是这么做的，你可以仿造这个写写。每个服务器对返回的状态码和消息格式都不一样，我这里没法写死，所以就得留给你们自己实现了。。

**Comment by jeasonlzy0216** [comment]
我知道你说的意思了。。。我怕也出现了这个问题。。这个问题的根源在于 JsonCallBack 中的 parseNetworkResponse 方法的具体实现。。他会自己解析用户传进来的泛型T，并返回对应的实体对象，一般情况下是没有问题的。。
但是，比如 DialogCallBAck<T> 继承了 GlobeCallBack<T>，而 GlobeCallBack<T> 才继承 JsonCallBack<T> 这时就会出现你说的问题，因为默认的 parseNetworkResponse 只能解析一层继承结构的泛型。向上面的两层，如果T 是 String，当代码运行时，parseNetworkResponse 会认为他的泛型是一个叫 T 的实体类，而不认为是一个泛型，所以代码进入了 Gson 解析。报出了 gson解析异常的错误。。
解决办法就是不用 JsonCallBack，parseNetworkResponse 每次请求的时候自己实现。虽然每次都得多写一个方法，但是不会出错。。感谢你的提问。。

**Comment by lostsakya** [comment]
帮你fix了这个bug。详见 (https://github.com/jeasonlzy0216/OkHttpUtils/pull/12)

问题：parseNetworkResponse()应该throws Exception。网络返回的数据往往不可靠，比如你想得到json数据，服务器给你返回一个404的错误页面。

解决方式：把parseNetworkResponse()的异常抛到onError和onAfter里了，框架使用者可以统一处理异常了。比如自定义一个ParseException, 在onError和onAfter里处理。
