### ISSUE TITLE
续传功能，退出APP重新下载

### ISSUE THREAD

**Issue by 925941723** [jeasonlzy0216/OkHttpUtils#40]
有续传功能吗，退出APP后可以在原来基础上继续下载吗

**Comment by jeasonlzy0216** [comment]
可以。目前最新版已经支持。

**Comment by reancool** [comment]
良心啊。还发现了 之前那个AppCacheUtils并不是十分好用，有时候会有丢失，使用Ache，感觉要好点，还没有看最新的代码，看到说断点功能优化了。试试看。
