### ISSUE TITLE
超时不走fail 和error 

### ISSUE THREAD

**Issue by baby2431** [jeasonlzy0216/OkHttpUtils#43]
你好~,我最近是在使用你的这个框架，做得很好。但是目前有一个问题。就是超时的时候 没有办法捕获到异常。希望作者能够解决下

**Comment by jeasonlzy0216** [comment]
超时直接走onError。。你可能没有复写这个方法。。

**Comment by jeasonlzy0216** [comment]
超时直接走onError。同时会把异常回掉回来。你可能没有复写这个方法。。
