### ISSUE TITLE
用户取消网络请求。

### ISSUE THREAD

**Issue by smarthityou** [jeasonlzy0216/OkHttpUtils#44]
当用户发起一次网络请求的时候，突然不然继续请求取消盖茨请求的时候，会执行哪个方法 @jeasonlzy0216

**Comment by jeasonlzy0216** [comment]
onError 回调。

**Comment by jeasonlzy0216** [comment]
已在1.8.0版本修复，目前对用户主动取消的请求不会回掉onError
