### ISSUE TITLE
Get请求在拼接地址多了& 符号

### ISSUE THREAD

**Issue by star95** [jeasonlzy0216/OkHttpUtils#46]
在HttpUtils的createUrlFromParams方法里
  `public static String createUrlFromParams(String url, Map<String, List<String>> params) {
        try {
            StringBuilder sb = new StringBuilder();
            sb.append(url);
            if (url.indexOf('&') > 0 || url.indexOf('?') > 0) sb.append("&");
            else sb.append("?");
            for (Map.Entry<String, List<String>> urlParams : params.entrySet()) {
                List<String> urlValues = urlParams.getValue();
                for (String value : urlValues) {
                    //对参数进行 utf-8 编码,防止头信息传中文
                    String urlValue = URLEncoder.encode(value, "UTF-8");
                    sb.append(urlParams.getKey()).append("=").append(urlValue).append("&");
                }
            }
            sb.deleteCharAt(sb.length() - 1);
            return sb.toString();
        } catch (UnsupportedEncodingException e) {
            OkLogger.e(e);
        }
        return url;
    }`
这句 if (url.indexOf('&') > 0 || url.indexOf('?') > 0) sb.append("&");
判断url含有 符号& 、?会加入&,是为了什么呢；

**Comment by jeasonlzy0216** [comment]
get请求拼接url参数
