### ISSUE TITLE
关于下载框架。。。

### ISSUE THREAD

**Issue by boylw123** [jeasonlzy0216/OkHttpUtils#49]
感谢大神框架，最近有个项目会用到多线程断点续传。。。一般手机应用（360手机市场）
有如下问题
1.如果做按钮及时更新（下载，继续，暂停，安装，打开。。。），按照demo的做法，会出现进度ui无法刷新的问题（因为第一次downloadinfo都为null，自已改了一下，但是没有成功）
2.demo没有判断第三方，或者直接删掉apk的情况。。。
急。。。大神求解！

**Comment by bozheng946448185** [comment]
你的解决了吗 我也 遇到差不多的问题了

**Comment by boylw123** [comment]
关于第三方删掉apk，可判断包名是否存在后者apk是否存在
但是：
1.假如时间过长，下载的task任务图标会显示不出来（ormlite-4.48）
2.下载进度还是无法更新。。。哭死

**Comment by boylw123** [comment]
关于第三方删掉apk，可判断包名是否存在或者apk是否存在
但是：
1.假如时间过长，下载的task任务图标会显示不出来（ormlite-4.48）
2.下载进度还是无法更新。。。哭死

**Comment by jeasonlzy0216** [comment]
用1.0.1版本的server已经去取了ormlite的依赖。。
