### ISSUE TITLE
session持久化

### ISSUE THREAD

**Issue by tangoox** [jeasonlzy0216/OkHttpUtils#5]
请问这个怎么能做到session持久化，我试了一下 把app进程杀死以后session就没了

**Comment by jeasonlzy0216** [comment]
session 默认是用的内存保存的，生命周期为该应用的进程生命周期，没有做文件的保存。如果需要session持久化。替换源码 cookie 包下的CookieJarImpl 实现，可以自己做文件缓存。

**Comment by jeasonlzy0216** [comment]
可以使用1.7.2 以上版本。。已经做了持久化。
