### ISSUE TITLE
如何查看历史版本号？

### ISSUE THREAD

**Issue by Tong-c** [jeasonlzy0216/OkHttpUtils#52]
使用框架时，添加的依赖为使用最新，更新之后，网络请求报错，但不知道之前的历史版本是多少，因为没有做封装，改起来会比较麻烦，所以希望提供历史版本号

**Comment by jeasonlzy0216** [comment]
历史版本号在项目主页的release中可以看。

**Comment by jeasonlzy0216** [comment]
目前你可以用   
okhttputils 1.7.2
okhttpserver 1.0.1 
解决更新后的问题
