### ISSUE TITLE
不支持上传文件同时，也带json参数？

### ISSUE THREAD

**Issue by deliangliao** [jeasonlzy0216/OkHttpUtils#54]
可以支持上传文件同时，也附带json参数吗？
用upJson(),不支持上传文件；
用form-data形式，参数只能是key-value形式，如何支持上传文件同时，也带json参数？
Thanks.

**Comment by jeasonlzy0216** [comment]
首先这样是不符合http规范的，如果确实要实现，那需要你们和服务器定义一套数据规范。。你这样传数据到服务端了。服务端怎么知道哪部分是图片哪部分是json呢。。
