### ISSUE TITLE
运行报错，大神帮忙看下呗，3Q

### ISSUE THREAD

**Issue by yangxiaoge** [jeasonlzy0216/OkHttpUtils#6]
1、 Cause: com.android.dex.DexException: Multiple dex files define Lcom/lzy/okhttputils/BuildConfig;
2、Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'F:\ZTEsoft\java\java64\jdk1.7\bin\java.exe'' finished with non-zero exit value 2

**Comment by memorise** [comment]
把compile project(':okhttputils')这句注释掉应该就可以了，因为okhttpserver里也引用了这个包，应该是重复引用包导致的，貌似新版本的Android Studio会有这个问题
