### ISSUE TITLE
仿照多路下载文件的方式下载 txt 会报DownloadManager.ERROR

### ISSUE THREAD

**Issue by Night-Kang** [jeasonlzy0216/OkHttpUtils#8]
看了下 通过OkHttpUtils.get(url).headers()  获取text/plain 文件里面是不带 contentLength()的，然后GG

**Comment by jeasonlzy0216** [comment]
contentlength是服务器主动返回的。不是客户端生成的。。

**Comment by Night-Kang** [comment]
是的，看了下http里面文本就不会带contentLength了，之后就会无法下载txt的文件了。
目前我这边的处理方法是自己设置totalLength了

**Comment by jeasonlzy0216** [comment]
如果要保证下载，是可以的，但是不返回 contentlength 是无法做进度监听的。
