### ISSUE TITLE
有个关于缓存的疑问

### ISSUE THREAD

**Issue by vihuela** [jeasonlzy0216/OkHttpUtils#9]
就是在CacheMode.DEFAULT下，按照标准的Http协议缓存，为什么不缓存成文件，我记得OKHttp原声就有缓存成文件的啊，难道新版本修改了？？

**Comment by jeasonlzy0216** [comment]
可以缓存成文件。。为了和其他缓存模式统一。。并对于手机版的缓存。很少使用304协议控制，都是自己主动做缓存，对于一般的服务器或项目，很少有服务端会对304响应做详细部署。。所以暂时不用原生的。。

**Comment by vihuela** [comment]
为什么手机版的缓存会很少使用304部署呢？？有何历史，求教
